// Generated by https://quicktype.io

export interface Users {
  id:       string;
  name:     string;
  address:  string;
  user:     string;
  password: string;
  email:    string;
  rol:      string;
}
